// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9mLl0Zlr3BAdUDq5RmRxx3Evqd-mC6s',
    appId: '1:657394662159:web:c2b2648428e08522bd1c7a',
    messagingSenderId: '657394662159',
    projectId: 'vsl-catena',
    authDomain: 'vsl-catena.firebaseapp.com',
    databaseURL: 'https://vsl-catena.firebaseio.com',
    storageBucket: 'vsl-catena.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFizwVbPra-yst4o5_8M6mSdP-lb84Lc',
    appId: '1:657394662159:android:da439b7652c34459bd1c7a',
    messagingSenderId: '657394662159',
    projectId: 'vsl-catena',
    databaseURL: 'https://vsl-catena.firebaseio.com',
    storageBucket: 'vsl-catena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj7xn2eyuogGsK5e6cLi3AsQJzY-tCfQU',
    appId: '1:657394662159:ios:edadf89d46545ed9bd1c7a',
    messagingSenderId: '657394662159',
    projectId: 'vsl-catena',
    databaseURL: 'https://vsl-catena.firebaseio.com',
    storageBucket: 'vsl-catena.appspot.com',
    androidClientId: '657394662159-4pndi8h1rka4g3ve5atidhno7ovun2v5.apps.googleusercontent.com',
    iosClientId: '657394662159-gevo3sogainubg2deel29rhh8h6ifhdt.apps.googleusercontent.com',
    iosBundleId: 'nl.vslcatena.app.vslcatena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj7xn2eyuogGsK5e6cLi3AsQJzY-tCfQU',
    appId: '1:657394662159:ios:274e35515af66a31bd1c7a',
    messagingSenderId: '657394662159',
    projectId: 'vsl-catena',
    databaseURL: 'https://vsl-catena.firebaseio.com',
    storageBucket: 'vsl-catena.appspot.com',
    androidClientId: '657394662159-4pndi8h1rka4g3ve5atidhno7ovun2v5.apps.googleusercontent.com',
    iosClientId: '657394662159-eppi8c7j0ddgf9k4e70r6h0oa5i2tll2.apps.googleusercontent.com',
    iosBundleId: 'nl.vslcatena.app.vslcatena.RunnerTests',
  );
}
