name: vslcatena
description: VSLCatena App
publish_to: 'none'
version: 1.0.0+1

scripts:
  build: dart pub get && dart run build_runner build -d
  generate: " "
  clean: dart run build_runner clean && flutter clean

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: '../domain'
  data:
    path: '../data'
  presentation:
    path: '../presentation'
  injectable:
  get_it:
  firebase_core: ^2.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

