name: Main workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/**'
      - develop
  pull_request:
    branches:
      - main
      - 'release/**'
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2.10.0
      - run: flutter pub get
      - run: dart pub global activate rps
      - run: rps build
      - run: rps generate
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
